---
title: "SCEPTRE_Preprocessing"
author: "Troy McDiarmid"
date: "2023-08-21"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(cowplot)
library(Matrix)
library(sceptre)
library(VGAM)
library(hdf5r)
library(Seurat)


library(usethis)

#usethis::edit_r_environ()

```


```{r}

##Read in data and create seurat object

data_dir <- '/Users/troymcdiarmid/Documents/Neurohub/Scaled_Screen/Scaled_Neuron_FBC_Matrix/'
list.files(data_dir)

CRISPRaQTL_Pilot_data <- Read10X(data.dir = data_dir)
CRISPRaQTL_Pilot_Seurat_Object = CreateSeuratObject(counts = CRISPRaQTL_Pilot_data$`Gene Expression`, min.cells = 100, min.features = 200, gene.column = 1)


```

```{r}
##Quantify mitochondrial DNA 

CRISPRaQTL_Pilot_Seurat_Object[["percent.mt"]] <- PercentageFeatureSet(CRISPRaQTL_Pilot_Seurat_Object, pattern = "^MT-")
```


```{r}
##Plot the amount of mitochondrial DNA

#plot1 <- FeatureScatter(CRISPRaQTL_Pilot_Seurat_Object, feature1 = "nCount_RNA", feature2 = "percent.mt")
#plot2 <- FeatureScatter(CRISPRaQTL_Pilot_Seurat_Object, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

#plot1 + geom_hex() + xlim(0,5000)

#plot2 + geom_hex()
```



```{r}
##Filtering for high quality cells 

CRISPRaQTL_Pilot_Seurat_Object_Subset <- subset(CRISPRaQTL_Pilot_Seurat_Object, subset = percent.mt < 20 & nCount_RNA > 900)

CRISPRaQTL_Pilot_Seurat_Object_Subset
```

```{r}
##Remove unnecessary Seurat objects in R environment

rm(CRISPRaQTL_Pilot_data, CRISPRaQTL_Pilot_Seurat_Object)

```


```{r}

##Reading in Feature Barcode Matrix

matrix_dir = "/Users/troymcdiarmid/Documents/Neurohub/Scaled_Screen/Scaled_Neuron_FBC_Matrix/"
barcode.path <- paste0(matrix_dir, "barcodes.tsv.gz")
features.path <- paste0(matrix_dir, "features.tsv.gz")
matrix.path <- paste0(matrix_dir, "matrix.mtx.gz")
mat <- readMM(file = matrix.path)
feature.names = read.delim(features.path,
                           header = FALSE,
                           stringsAsFactors = FALSE)
barcode.names = read.delim(barcode.path,
                           header = FALSE,
                           stringsAsFactors = FALSE)
colnames(mat) = barcode.names$V1
rownames(mat) = feature.names$V1

```

```{r}
##Fiiltering the FBC matrix for detected genes

Detected_Genes <- rownames(CRISPRaQTL_Pilot_Seurat_Object_Subset)

genes <- read.table("/Users/troymcdiarmid/Documents/Neurohub/Scaled_Screen/Scaled_Neuron_FBC_Matrix/features.tsv.gz", fill = TRUE, stringsAsFactors = FALSE) %>% 
   filter(V2 %in% Detected_Genes)

Detected_Genes <- genes$V1
```


```{r}
##Indexing the matrix for only high quality cells seurat object (x is the index vector of high quality cell names)

x <- rownames(CRISPRaQTL_Pilot_Seurat_Object_Subset@meta.data)

Seurat_Filtered_FBC_Mat <- mat[ ,x]


```

```{r}
##Creating a gRNA Matrix 

Ft_Ref <- read_csv("/Users/troymcdiarmid/Documents/Neurohub/Scaled_Screen/Cell_Ranger_Scripts_And_Outputs/Cellranger_Input_Files/feat_ref_200_char_final.csv")  %>% 
    rename(gRNA = id)
    
x <- Ft_Ref$gRNA

gRNA_matrix <- Seurat_Filtered_FBC_Mat[x, ]


```


```{r}
##Calculating MOI

MOI_Mat <- colSums(gRNA_matrix > 5)

MOI_DF <- as.data.frame(as.table(MOI_Mat))

MOI_DF <- MOI_DF %>%  
    rename(Cell = Var1) %>% 
    rename(MOI = Freq)  

summary(MOI_DF)


##Calculate assignment rate (the proportion of cells with 1 or more gRNA)

Assignment_Rate <- 1 - (sum(MOI_DF == 0 ) / length(MOI_DF$MOI))

Assignment_Rate


##Creating an MOI plot

options(repr.plot.width=7, repr.plot.height=6)

ggplot(MOI_DF, aes(x = MOI)) +
  geom_histogram(colour = "#56B4E9", fill = "#56B4E9", binwidth = 1) +  
  theme_classic() +
  xlim(-1,60) +
  theme(axis.line = element_line(colour = 'black', size = 0.7)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.7)) +
  theme(axis.ticks.length=unit(.25, "cm")) +
  labs(title = "", x = "", y = "") +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 24)) 


##Same plot as above without text labels for final figure

options(repr.plot.width=7, repr.plot.height=6)

ggplot(MOI_DF, aes(x = MOI)) +
  geom_histogram(colour = "#D1D4D4", fill = "#D1D4D4", binwidth = 1) +  
  theme_classic() +
  xlim(-1,60) +
  theme(axis.line = element_line(colour = 'black', size = 0.7)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.7)) +
  theme(axis.ticks.length=unit(.25, "cm")) +
  theme(axis.text = element_blank()) +
  labs(title = "", x = "", y = "") 



##Calculating the number of cells with each perturbation

N_Cells_With_Pert_Mat <- rowSums(gRNA_matrix > 5)

N_Cells_With_Pert_DF <- as.data.frame(as.table(N_Cells_With_Pert_Mat))

N_Cells_With_Pert_DF <- N_Cells_With_Pert_DF %>%  
    rename(Gene = Var1) %>% 
    rename(N_Cells_With_Perturbation = Freq)  

summary(N_Cells_With_Pert_DF)


##Then making a plot of the number of cells per perturbation

options(repr.plot.width=7, repr.plot.height=6)

ggplot(N_Cells_With_Pert_DF, aes(x = N_Cells_With_Perturbation)) +
  geom_histogram(colour = "#56B4E9", fill = "#56B4E9", binwidth = 10) +  
  theme_classic() +
  xlim(-10,501) +
  theme(axis.line = element_line(colour = 'black', size = 0.7)) +
  theme(axis.ticks.y = element_line(colour = "black", size = 0.7)) +
  theme(axis.ticks.length=unit(.25, "cm")) +
  labs(title = "", x = "", y = "") +
  theme(axis.text = element_text(family="Arial", colour = "black", size = 24)) 


##Same plot as above without axis text for final figure
options(repr.plot.width=7, repr.plot.height=6)


ggplot(N_Cells_With_Pert_DF, aes(x = N_Cells_With_Perturbation)) +
  geom_histogram(colour = "#D1D4D4", fill = "#D1D4D4", binwidth = 10) +  
  theme_classic() +
  xlim(-10,501) +
  theme(axis.line = element_line(colour = 'black', size = 0.7)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.7)) +
  theme(axis.text = element_blank()) +
  theme(axis.ticks.length=unit(.25, "cm")) +
  labs(title = "", x = "", y = "") 


```


```{r}

##Create gene matrix

##Include only detected genes in the gene matrix and remove the gRNAs from the gene matrix

Seurat_Filtered_FBC_Mat <- Seurat_Filtered_FBC_Mat[Detected_Genes, ]
gene_matrix <- Seurat_Filtered_FBC_Mat[-which(rownames(Seurat_Filtered_FBC_Mat) %in% x), ]

```



```{r}
# covariance matrix
lg_gene_lib_size <- log(colSums(gene_matrix))
lg_gRNA_lib_size <- log(colSums(gRNA_matrix))
lg_non_zero_genes <- log(colSums(gene_matrix>0))
lg_non_zero_sgRNA <- log(colSums(gRNA_matrix>0))


lane <- as.data.frame(colnames(CRISPRaQTL_Pilot_Seurat_Object_Subset)) %>% 
    separate(`colnames(CRISPRaQTL_Pilot_Seurat_Object_Subset)`, into = c("Garbage", "lane"), sep = "-" )

lane <- as.factor(lane$lane)  

p_mito <- CRISPRaQTL_Pilot_Seurat_Object_Subset$percent.mt

covariate_matrix <- data.frame(lg_gRNA_lib_size,
                                  lg_non_zero_sgRNA,
                                  lg_gene_lib_size,
                                  lg_non_zero_genes,
                                  p_mito,
                                  lane)
```


```{r}
##Removing things in environment to remove strain on memory 

rm(CRISPRaQTL_Pilot_data, CRISPRaQTL_Pilot_Seurat_Object, CRISPRaQTL_Pilot_Seurat_Object_Subset, mat, plot1, plot2, MOI_DF, MOI_Mat, N_Cells_With_Pert_Mat, N_Cells_With_Pert_DF)


```

```{r}
# identification and removal of cells w/o sgRNA detected
cells_wo_sgRNA_id <- covariate_matrix$lg_non_zero_sgRNA>-Inf

covariate_matrix <- covariate_matrix[cells_wo_sgRNA_id,]
gRNA_matrix <- gRNA_matrix[,cells_wo_sgRNA_id]
gene_matrix <- gene_matrix[,cells_wo_sgRNA_id]

```


```{r}

saveRDS(gRNA_matrix, "/Users/troymcdiarmid/Documents/Neurohub/Scaled_Screen/SCEPTRE_Processed_Matrices/Scaled_Screen_gRNA_Matrix.mtx")
saveRDS(gene_matrix, "/Users/troymcdiarmid/Documents/Neurohub/Scaled_Screen/SCEPTRE_Processed_Matrices/Scaled_Screen_gene_Matrix.mtx")
saveRDS(covariate_matrix, "/Users/troymcdiarmid/Documents/Neurohub/Scaled_Screen/SCEPTRE_Processed_Matrices/Scaled_Screen_covariate_Matrix.mtx")

```

```{r}
gRNA_matrix <- read_rds("/Users/troymcdiarmid/Documents/Neurohub/Scaled_Screen/SCEPTRE_Scaled_Neuron_Screen_Analysis/Processed_Matrices/Scaled_Screen_gRNA_Matrix.mtx")
gene_matrix <- read_rds("/Users/troymcdiarmid/Documents/Neurohub/Scaled_Screen/SCEPTRE_Scaled_Neuron_Screen_Analysis/Processed_Matrices/Scaled_Screen_gene_Matrix.mtx")
covariate_matrix <- read_rds("/Users/troymcdiarmid/Documents/Neurohub/Scaled_Screen/SCEPTRE_Scaled_Neuron_Screen_Analysis/Processed_Matrices/Scaled_Screen_covariate_Matrix.mtx")
```


